### ISSUE TITLE
Scroll commands that don't conflict with Mission Control on Mac

### ISSUE THREAD

**Issue by codekiln** [FloppyDisco/git-stage-file#18]
Thanks for the great plugin; I'm enjoying it so far. 

Posting this as an assist to other mac devs using this plugin. 

The mac defaults `Ctrl+Up` and `Ctrl+Down` for this plugin conflict with built-in keyboard shortcuts on macOS, where the Control + Up Arrow and Control + Down Arrow keyboard shortcuts are used to navigate between spaces and Mission Control. Specifically, Control + Up Arrow opens Mission Control, displaying all open windows and spaces, while Control + Down Arrow shows all windows of the frontmost application. 
See also [Mac keyboard shortcuts - Apple Support](https://support.apple.com/en-us/102650?utm_source=chatgpt.com).

I really wish there was an AI-assisted way to suggest new good keyboard shortcuts.  I remapped scroll up and scroll down to ctrl+opt+up and ctrl+opt+down, respectively. Hopefully I can live with that. 

from keybindings.json:
```json
[
    {
        "key": "ctrl+alt+down",
        "command": "quickStage.scrollDown",
        "when": "QuickStageVisible"
    },
    {
        "key": "ctrl+down",
        "command": "-quickStage.scrollDown",
        "when": "QuickStageVisible"
    },
    {
        "key": "ctrl+alt+up",
        "command": "quickStage.scrollUp",
        "when": "QuickStageVisible"
    },
    {
        "key": "ctrl+up",
        "command": "-quickStage.scrollUp",
        "when": "QuickStageVisible"
    }
]
```

**Comment by FloppyDisco** [comment]
@codekiln 
ooph! 🤦🏻‍♂️ 
nice catch.
I think, I removed those keybindings on my machine, and didn't think to check for global conflicts when writing this.

i think I'm just going to change these to (Option). I don't think there is any need to get more complicated than that?

**Comment by FloppyDisco** [comment]
shortcuts changed with `0.3.11` thanks for pointing this out!
they are now set to Option + Arrow Keys.
