### ISSUE TITLE
Select next file in list on stage, not previous

### ISSUE THREAD

**Issue by dannypernik** [FloppyDisco/git-stage-file#19]
This is super nitpicky, but that's why this extension exists, right? When I skip one or more files and stage one below it, the file below the staged file should be selected. Currently, the previous file, which I skipped over and do not need to stage, is selected instead. This results in one whole extra keypress per file. 

https://github.com/user-attachments/assets/57e49cca-d1af-4b39-a36f-8c667f7d6109

**Comment by FloppyDisco** [comment]
@dannypernik 
you are correct. it should definitely do that. I remember thinking that when i was writing this.
I'm using the Quick Pick interface in a really unorthodox way and it made managing the index of the selection very tedious. I settled for the current behavior at the time to move on with getting the rest of it working. let me go back and take another look at it now, and see if I can get it to play nice.

**Comment by FloppyDisco** [comment]
fixed with `0.3.13`
it should now have better indexing when selecting a file.

**Comment by dannypernik** [comment]
Splendid, thank you!
