### ISSUE TITLE
Show diff when staging

### ISSUE THREAD

**Issue by dannypernik** [FloppyDisco/git-stage-file#3]
Hi, thank you for making this! I would like for the diff view to open when a file is staged. This would mimic the native behavior. Hopefully this view can be opened while the git quickstage menu remains displayed. Not sure if you would prefer for this to be the default or optional. Perhaps there's a built-in setting that can be respected?

![Screenshot 2024-10-30 at 4 10 28 AM](https://github.com/user-attachments/assets/ad14787f-cf87-4a06-9838-304db978c22f)

**Comment by FloppyDisco** [comment]
> Hi, thank you for making this! I would like for the diff view to open when a file is staged. 

thank you! I'm glad someone is using it! lol.
I also wanted to integrate the diff feature into this but I'm having some trouble getting it to work. 

tell me more about how you would like this to behave, do you want the diffed file to open as you scroll through the files in the picker. or only if you select a file in the picker? 
I was thinking that the space bar would diff the file when it was highlighted but NOT Stage/Unstage it, that way you could diff some files, review them, and then go back to stage them separately

**Comment by dannypernik** [comment]
My expectation was that the diff would be shown on Enter, same as if a filename is clicked in scm. I think this is most similar to native and thus makes sense as a default. What if the diff was "previewed" prior to staging if Shift is held while navigating up/down through the list? That way it wouldn't require an extra click of the spacebar.

**Comment by FloppyDisco** [comment]
that makes sense. I'm thinking "stage and diff" on (enter) and "stage no diff" on (Space). I really like the idea of the changes popping open as you navigate though, that feels very smooth. i'm gonna see if i can get that working. the first step is getting the diff function to work inside vs code which i have not been able to do yet.

**Comment by FloppyDisco** [comment]
I got diff the diff tool to work! more to follow. 

<img width="1390" alt="Screenshot 2024-11-01 at 11 48 11 PM" src="https://github.com/user-attachments/assets/4bb5ddee-d0a7-48d4-8589-442d02f604f5">

**Comment by FloppyDisco** [comment]
The new version now has a diff feature, it previews the file in the background. and you stage/unstage with `space`. `enter` will pass focus to the diff editor. let me know what you think!

**Comment by dannypernik** [comment]
I love the diff preview! Not sure if everyone will love it but I guess you can just wait and see if anyone complains.

However, I don't like that enter essentially acts as a close button for quickstage. I expect enter to stage the focused file. I think escape would be the most natural choice to pass focus to the diff editor.

**Comment by FloppyDisco** [comment]
So my thought was to make this behave exactly like the list of changes in the Git sidebar, just with a keybinding for each  command.   When you press enter in the list of changes it opens the diff, so that's what i went with. So you think (Enter) should toggle stage/unstage and (Esc) should close QuickStage and move focus to the Diff. 

one of the other complaints i have read only, is people wanting a way to stage/unstage files WITHOUT opening a diff editor, because that is actually the functionality that is not really provided by the scm sidebar. i'm not sure how to satisfy both requirements here!

**Comment by FloppyDisco** [comment]
I took your suggestions and swapped the controls around. see my other comment in #5 . Check out the Readme for the updated controls.
