### ISSUE TITLE
not staging new file

### ISSUE THREAD

**Issue by FloppyDisco** [FloppyDisco/git-stage-file#4]
<img width="1378" alt="Screenshot 2024-10-30 at 11 27 13 AM" src="https://github.com/user-attachments/assets/c7e51200-59c7-4097-a3a4-8960e828c5ff">

**Comment by FloppyDisco** [comment]
<img width="1430" alt="Screenshot 2024-10-30 at 11 25 09 AM" src="https://github.com/user-attachments/assets/a97ae676-2537-4b96-9ae8-4a43e7af856f">

mine seems to be staging new files.
are you in a workspace that has multiple folders open? or maybe with multiple git repositories?
does it fail every time, or just some times?

**Comment by dannypernik** [comment]
Ah. I believe the issue is that the new files are in a folder that is empty and thus does not yet exist in the repo.

**Comment by FloppyDisco** [comment]
ok. I will try that out. I'm thinking I will upgrade this to use `simple-git` it might streamline some of these issues.

**Comment by FloppyDisco** [comment]
@dannypernik 
I was actually able to convert the entire extension over to use the vscode.git.extension API. ( I had tried previously, and was unsuccessful) now that it uses the native commands, it should be alot more robust with things like this. i'm gonna close this issue. please download the new version! `0.3.0`. also i changed up all of the controls so check out the readme!
